let questions = [
    "Do you eat?",
    "Have you ever?",
    "But will you?",
    "Do you find joy being around others?",
    "Do you ever think about being married for life?",
    "Do you ever let the voices win?",
    "Have you ever sacrificed a small child in the name of a greater being?",
    "Are your lips really kissable? Like, really soft and kissable? Pillowy, soft, kissable lips? Kiss?",
    "Have you ever thought about taking someones life because they took your reeses pieces from twelve years ago screw you Thomas I still remember that you prick anyways would you?",
    "Do you put extra salt or other seasonings on food?",
    "Ever think about robbing a bank for the fun of it?",
    "Do you go to bed early or late?",
    "Where is your favorite spot to hang out? Wait fuck this is a yes or no thing answer yes for beach answer no for you are a sad little disappointment.",
    "If the person of your dreams said they did not love you, would you still try to pursue a life with them in some way?",
    "Do you ever claw at your eyes?",
    "Ever try finger but hole?",
    "Have you ever thought about how?",
    "For anything in the world, would you send me feet pics?",
    "Yes?",
    "Did you really think that this was all of your own free will?",
    "Do you recognize this beat? do, do - dodo do, do - dodo do, do - dodo do, do - dodo",
    "Do you avoid sharing your interests with others?",
    "Is eye contact difficult for you to maintain?",
    "When speaking, do you stumble over words or stutter often?",
    "When a plan does not go your way, do you show excessive anger?",
    "Would you do everything you possibly could for your loved one(s), even if it meant making sacrifices?",
    "Are one of your favorite hobbies to cook?",
    "Before bed, do you put any electronic devices away an hour in advance?",
    "Do you respect others privacy and needs?",
    "Have you ever denied being in need of help because you fear bothering others?",
    "Do you often spend time with others?",
    "Can you see yourself in the future being happy?",
    "Do you turn off lights or devices the moment they are not being used?",
    "Do you leave the television on for background noise?",
    "Are you afraid of animals or people much larger than you?",
    "Have you thought of learning a new language for fun?",
    "Do you enjoy spicy foods?",
    "Have you drank water today? (If not, be sure to do so; Self-care is important.)",
    "Is it socially acceptable to make fun of the British?",
    "Is Twitter in your opinion turning into a complete shithole?",
    "Ever play Obfuscation 100?",
    "Can you program your own games?",
    "Wanna hear a knock-knock joke?",
    "Did you know: Every copy of Super Mario 64 is personalized?",
    "Do you BELIIEEEEEVE in love after love?",
    "Does the thought of holding hands make you feel nervous?",
    "Have intrusive thoughts ever told you that you should eat the spoiled deviled egg on the windowsill?",
    "Ever go to a school book fair and steal something small like an eraser? Like something so small that no one would notice?",
    "Are your hands really sweaty right now?",
    "Do the slightest memories cause you to abandon all hope of ever being a stripper?",
    "Do you ever touch fire just to feel something?",
    "If you could, would you?",
    "Will you marry me?",
    "I'll give you $100 to fuck off. Deal?",
    "Do your friends call you the throat goat?",
    "Is it long though?"
]